# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [3]:
import numpy as np

In [68]:
def BMI(h, w):
    h = np.array(h)
    w = np.array(w)
    return ((w / (h**2)) * 730)

In [69]:
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]

print(BMI(height, weight))


[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [ ]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""

In [1]:
def make_matrix(low,high,shape = None, data_type = float):
    if shape == None:
        shape = (np.random.randint(1, 10), np.random.randint(1, 10))
    output = np.random.uniform(low, high, shape)

    return output.astype(data_type)

In [4]:
#3x3 matrix filled with random floats between 0 and 15
make_matrix(0,15,(3,3))

array([[ 0.32636694,  6.08833523,  8.93739025],
       [ 4.05777721,  4.69257901,  3.47163524],
       [11.28335526, 10.43101582,  8.17188472]])

In [6]:
#undefined matrix shape with information between 0, 10, data type of int
make_matrix(0,10, data_type = int)

array([[3, 9],
       [9, 2],
       [5, 4],
       [4, 2],
       [5, 4],
       [1, 3],
       [2, 8],
       [4, 5],
       [4, 7]])

In [8]:
# Matrix with shpae of (4, 10), data type of int, information between 0 and 15
make_matrix(0,15,(4,10), int)

array([[ 4,  3,  2, 13,  6,  6,  1,  5,  6,  8],
       [ 9,  6,  6,  5,  4, 11,  5,  4,  2,  8],
       [ 1,  8, 14,  6,  2,  9, 12,  2,  6,  2],
       [ 2, 13,  3, 13,  5,  8,  9,  7, 13,  9]])

### #3 - Extra: Open and load the data in for the 2021 White Sox. Create a function that takes in a category (i.e. 'H' or 'HR' or '2B') and returns the average for the team

In [76]:
import csv
import numpy as np

#Test to make sure you have the correct data



In [82]:

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|U25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def open_csv_as_ndarray(filename, d=','):
    data = np.genfromtxt(filename, delimiter=d, names=FIELDS, dtype=DATATYPES, skip_header=1, encoding='utf-8')
    return data

sox21 = open_csv_as_ndarray('whitesox_2021_hitting.csv')
sox21

array([( 1, b'C', 'Yasmani Grandal', 32,  93, 375, 279, 60,  67,  9, 0, 23,  62,  0, 0, 87,  82, 0.24 , 0.42 , 0.52 , 0.939, 157, 145, 15,  3, 1,  5, 0),
       ( 2, b'1B', 'José Abreu', 34, 152, 659, 566, 86, 148, 30, 2, 30, 117,  1, 0, 61, 143, 0.261, 0.351, 0.481, 0.831, 125, 272, 28, 22, 0, 10, 3),
       ( 3, b'2B', 'Cesar Hernandez', 31,  53, 217, 194, 24,  45,  4, 0,  3,  15,  1, 1, 21,  45, 0.232, 0.309, 0.299, 0.608,  69,  58,  5,  1, 0,  1, 2),
       ( 4, b'SS', 'Tim Anderson', 28, 123, 551, 527, 94, 163, 29, 2, 17,  61, 18, 7, 22, 119, 0.309, 0.338, 0.469, 0.806, 118, 247,  5,  1, 0,  1, 1),
       ( 5, b'3B', 'Yoan Moncada', 26, 144, 616, 520, 74, 137, 33, 1, 14,  61,  3, 2, 84, 157, 0.263, 0.375, 0.412, 0.787, 117, 214,  6, 10, 0,  2, 1),
       ( 6, b'LF', 'Andrew Vaughn', 23, 127, 469, 417, 56,  98, 22, 0, 15,  48,  1, 1, 41, 101, 0.235, 0.309, 0.396, 0.705,  92, 165, 14,  6, 0,  5, 0),
       ( 7, b'CF', 'Luis Robert', 23,  68, 296, 275, 42,  93, 22, 1, 13,  43,  6, 1,

In [86]:
def get_team_average(cat):
    alist = sox21[cat]
    return sum(alist) / len(alist)

print(get_team_average('H')) # 57.0
print(get_team_average('HR')) # 7.916666666666667
print(get_team_average('2B')) # 11.416666666666666

57.0
7.916666666666667
11.416666666666666
